In [12]:
import pandas as pd
import os
import datetime

In [95]:
def date_time(date):
    if type(date) is datetime.datetime:
        return date
    elif type(date) is str:
        try:
            return datetime.datetime.strftime(date,'%d-%m-%Y')
        except:
            try:
                return datetime.datetime.strptime(date,'%Y-%m-%d %H:%M:%S').strftime('%d-%m-%Y')
            except:
                return None

In [96]:
type('da')

str

In [97]:
PLANETS_PATH = "./LotteryProject/planets_eng.csv"
MOON_PATH = "./LotteryProject/moon_cycles.csv"
LOTTERY_PATH = "./LotteryProject/LotteryData/"

data_planet = pd.read_csv(PLANETS_PATH)
moon_data = pd.read_csv(MOON_PATH)

lottery_files = {}
for file in os.listdir(LOTTERY_PATH):
    tmp = pd.read_csv(LOTTERY_PATH+file)
    tmp.Date = tmp.Date.apply(date_time)
    tmp = tmp[tmp.Date!=None]
#     tmp.Date = pd.to_datetime(tmp.Date).
    lottery_files[file.split('.')[0]] = tmp
LOTTERY_NAMES = [i for i in lottery_files.keys()]

In [80]:
tmp.Date.isnull().mean()

0.19174247725682295

In [81]:
lottery_files[LOTTERY_NAMES[-1]]

,Unnamed: 0,URL,Lottery Name,Date,Tier,Match,Winners,Amount,Numbers,Extra Numbers
0,0,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,2021-03-21,I,8 Numbers,119000000.0,NaN,"[2, 6, 3, 7, 9, 3, 8, 6]",NaN
1,1,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,2021-03-21,II,7 Numbers,1000000.0,NaN,"[2, 6, 3, 7, 9, 3, 8, 6]",NaN
2,2,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,2021-03-21,III,6 Numbers,100000.0,NaN,"[2, 6, 3, 7, 9, 3, 8, 6]",NaN
3,3,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,2021-03-21,IV,5 Numbers,10000.0,NaN,"[2, 6, 3, 7, 9, 3, 8, 6]",NaN
4,4,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,2021-03-21,V,4 Numbers,1000.0,NaN,"[2, 6, 3, 7, 9, 3, 8, 6]",NaN
...,...,...,...,...,...,...,...,...,...,...
2853,2853,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,NaT,IV,Last 5 Numbers,5000.0,NaN,"[3, 3, 2, 4, 0, 6, 2, 8]",NaN
2854,2854,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,NaT,V,Last 4 Numbers,500.0,NaN,"[3, 3, 2, 4, 0, 6, 2, 8]",NaN
2855,2855,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,NaT,VI,Last 3 Numbers,50.0,NaN,"[3, 3, 2, 4, 0, 6, 2, 8]",NaN
2856,2856,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,NaT,VII,Last 2 Numbers,7.5,NaN,"[3, 3, 2, 4, 0, 6, 2, 8]",NaN
2857,2857,https://www.lottoland.com/en/worldmillions/res...,WorldMillions,NaT,VIII,Last Number,5.0,NaN,"[3, 3, 2, 4, 0, 6, 2, 8]",NaN